// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlantWatch.Infrastructure.Persistence;

#nullable disable

namespace PlantWatch.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PlantWatchDbContext))]
    partial class PlantWatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlantWatch.Domain.Machines.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<double>("IdealCycleSeconds")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("PlantWatch.Domain.Machines.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<int>("PiecesProduced")
                        .HasColumnType("integer");

                    b.Property<int>("RejectedPieces")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_sensor_readings_machine_timestamp");

                    b.ToTable("sensor_readings", (string)null);
                });

            modelBuilder.Entity("PlantWatch.Domain.Machines.StopEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "StartedAt");

                    b.ToTable("stop_events", (string)null);
                });

            modelBuilder.Entity("PlantWatch.Domain.Machines.SensorReading", b =>
                {
                    b.HasOne("PlantWatch.Domain.Machines.Machine", "Machine")
                        .WithMany("Readings")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("PlantWatch.Domain.Machines.StopEvent", b =>
                {
                    b.HasOne("PlantWatch.Domain.Machines.Machine", "Machine")
                        .WithMany("StopEvents")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("PlantWatch.Domain.Machines.Machine", b =>
                {
                    b.Navigation("Readings");

                    b.Navigation("StopEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
